{% set name = "qhub" %}
{% set version = "0.1.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qhub-{{ version }}.tar.gz
  sha256: 054548fcd614bef3028d2a5413cf2fae44f2e5751db5b960db47818a102f794e

build:
  number: 0
  noarch: python
  entry_points:
    - qhub = qhub.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3,<4.0
    - pip
  run:
    - python >=3,<4.0
    - auth0-python
    - cloudflare
    - cookiecutter
    - pydantic
    - pynacl
    - pyyaml

test:
  imports:
    - qhub
    - qhub.cli
  commands:
    - pip check
    - qhub --help
  requires:
    - pip

about:
  home: https://github.com/quansight/qhub
  summary: Management of QHub on Cloud Infrastructure
  dev_url: https://github.com/quansight/qhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
