{% set name = "qhub" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qhub-{{ version }}.tar.gz
  sha256: 207556a95063522963a314edd175fe8e1daac8bdcb2d6bf746416672249d1c83

build:
  number: 0
  noarch: python
  entry_points:
    - qhub = qhub.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3,<4.0
    - pip
  run:
    - python >=3,<4.0
    - auth0-python
    - cloudflare
    - cookiecutter
    - pydantic
    - pynacl
    - pyyaml

test:
  imports:
    - qhub
    - qhub.cli
  commands:
    - pip check
    - qhub --help
  requires:
    - pip

about:
  home: https://github.com/quansight/qhub
  summary: Management of QHub on Cloud Infrastructure
  dev_url: https://github.com/quansight/qhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
