{% set name = "qhub" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qhub-{{ version }}.tar.gz
  sha256: ef1ea008ac1edf43d125539f7b7432eeb342dbd3339f44787411e19c8de94fa1

build:
  number: 0
  noarch: python
  entry_points:
    - qhub = qhub.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.10
    - pip
  run:
    - python >=3.7,<3.10
    - ruamel.yaml
    - cloudflare
    - auth0-python
    - pydantic
    - pynacl
    - bcrypt
    - kubernetes
    - azure-identity ==1.6.1
    - azure-mgmt-containerservice ==16.2.0
    - boto3
    - python-keycloak
    - importlib_metadata

test:
  imports:
    - qhub
    - qhub.cli
  commands:
    - pip check
    - qhub --help
  requires:
    - pip

about:
  home: https://github.com/quansight/qhub
  summary: Management of QHub on Cloud Infrastructure
  dev_url: https://github.com/quansight/qhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - tylerpotts
    - costrouc
    - danlester
    - aktech
    - viniciusdc
    - iameskild
