{% set name = "qhub" %}
{% set version = "0.3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qhub-{{ version }}.tar.gz
  sha256: fc8e0baabfb7528eb50f6344c24a60a51ae2f92b707471591a51264df118841f

build:
  number: 0
  noarch: python
  entry_points:
    - qhub = qhub.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - auth0-python
    - bcrypt
    - cloudflare
    - cookiecutter
    - pydantic
    - pynacl
    - ruamel.yaml

test:
  imports:
    - qhub
    - qhub.cli
  commands:
    - pip check
    - qhub --help
  requires:
    - pip

about:
  home: https://github.com/quansight/qhub
  summary: Management of QHub on Cloud Infrastructure
  dev_url: https://github.com/quansight/qhub
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
